/** Supabase 연결 실패 시 사용하는 로컬 문답 데이터 */
export const FALLBACK_QUIZZES = [
  {
    question_number: 1,
    question: '눈을 뜨니 아무것도 없는 황폐지입니다. 가장 먼저 무엇을 찾겠습니까?',
    option1: '식량과 물',
    option2: '안전한 거주지',
    option3: '지나가는 사람',
    option4: '타고 이동할 수단',
    type1: 'combat',
    type2: 'strategy',
    type3: 'survival',
    type4: 'modern',
  },
  {
    question_number: 2,
    question: '저 멀리서 정체불명의 괴생명체가 이쪽을 향해 뛰어옵니다. 당신의 반사적인 행동은?',
    option1: '주변의 몽둥이를 쥐고 맞서 싸운다',
    option2: '들키지 않게 바위 뒤로 숨는다',
    option3: '반대 방향으로 무작정 도망친다',
    option4: '현대 물건(라이터 등)을 던져 교란한다',
    type1: 'combat',
    type2: 'strategy',
    type3: 'survival',
    type4: 'modern',
  },
  {
    question_number: 3,
    question: '밤이 되자 엄청난 추위가 찾아왔습니다. 체온을 유지하기 위해 무엇을 하겠습니까?',
    option1: '나무를 비벼서라도 어떻게든 불을 피운다',
    option2: '땅을 파거나 동굴을 찾아 들어간다',
    option3: '얼어 죽지 않게 밤새도록 몸을 움직인다',
    option4: '주변의 풀이나 낙엽을 덮고 버틴다',
    type1: 'combat',
    type2: 'strategy',
    type3: 'survival',
    type4: 'modern',
  },
  {
    question_number: 4,
    question: '길을 걷다 목이 너무 마른데, 색깔이 보라색인 수상한 샘물을 발견했습니다. 어떻게 하겠습니까?',
    option1: '목말라 죽느니 일단 마시고 본다',
    option2: '독이 있는지 손만 살짝 담가본다',
    option3: '주변 동물이 마시는지 지켜본다',
    option4: '쳐다보지도 않고 지나친다',
    type1: 'combat',
    type2: 'strategy',
    type3: 'survival',
    type4: 'modern',
  },
  {
    question_number: 5,
    question: '이세계의 마을에 겨우 도착했지만, 돈이 하나도 없습니다. 당장 무엇부터 하겠습니까?',
    option1: '몸으로 때우는 거친 일꾼 자리를 구한다',
    option2: '현대 지식(수학, 과학 등)을 팔아 장사를 한다',
    option3: '지나가는 사람에게 구걸하며 도움을 요청한다',
    option4: '다시 위험한 숲으로 나가 사냥을 시도한다',
    type1: 'combat',
    type2: 'strategy',
    type3: 'survival',
    type4: 'modern',
  },
  {
    question_number: 6,
    question: "누군가 당신의 유일한 현대 물건인 '스마트폰'을 훔쳐 달아납니다. 어떻게 하겠습니까?",
    option1: '지구 끝까지 쫓아가서 멱살을 잡는다',
    option2: '"도둑이야!" 하고 주변에 소리쳐 도움을 구한다',
    option3: '어차피 인터넷도 안 터지니 쿨하게 포기한다',
    option4: '밤에 그 녀석의 처소에 몰래 들어가 훔쳐온다',
    type1: 'combat',
    type2: 'strategy',
    type3: 'survival',
    type4: 'modern',
  },
  {
    question_number: 7,
    question: '당신이 인생에서 가장 견디기 힘든 두려움은 무엇입니까?',
    option1: '몸이 찢어지는 듯한 육체적 고통',
    option2: '아무도 없는 곳에 혼자 남겨지는 외로움',
    option3: '내 힘으로 아무것도 바꿀 수 없는 무력함',
    option4: '앞으로 어떻게 될지 모르는 불확실함',
    type1: 'combat',
    type2: 'strategy',
    type3: 'survival',
    type4: 'modern',
  },
  {
    question_number: 8,
    question: '눈앞에 화려한 보물상자와 먼지가 쌓인 낡은 책 한 권이 있습니다. 무엇을 고르겠습니까?',
    option1: '당장 부자가 될 수 있는 화려한 보물상자',
    option2: '이 세계의 비밀이 담겨있을 것 같은 낡은 책',
    option3: '욕심을 내어 둘 다 가방에 쑤셔 넣는다',
    option4: '함정일지도 모르니 둘 다 건드리지 않는다',
    type1: 'combat',
    type2: 'strategy',
    type3: 'survival',
    type4: 'modern',
  },
  {
    question_number: 9,
    question: '갑자기 온몸의 혈관을 타고 알 수 없는 뜨거운 기운이 소용돌이칩니다. 이 에너지를 어떻게 통제하겠습니까?',
    option1: '주변을 향해 강력하게 힘을 내지른다',
    option2: '온몸으로 힘을 흡수하며 가만히 숨을 고른다',
    option3: '발을 굴러 땅속으로 힘을 분출한다',
    option4: '참지 못하고 하늘을 향해 크게 소리를 지른다',
    type1: 'combat',
    type2: 'strategy',
    type3: 'survival',
    type4: 'modern',
  },
  {
    question_number: 10,
    question: '마지막 질문입니다. 여신이 당신의 운명을 확정 짓기 직전, 마음속으로 간절히 빌어본 한마디는?',
    option1: '"그 누구도 나를 건드릴 수 없는 압도적인 강함을 주세요."',
    option2: '"위험한 상황이 오면 언제든 도망칠 수 있는 탈출 능력을 주세요."',
    option3: '"상처받아도 금방 나을 수 있는 불사신의 신체를 주세요."',
    option4: '"다 필요 없고, 그냥 원래 살던 현대 집으로 보내주세요."',
    type1: 'combat',
    type2: 'strategy',
    type3: 'survival',
    type4: 'modern',
  },
]
